// Generated by Glove Foundry. Do not edit.
export type FoundryRoutes = {
  readonly "release-planner": typeof import("../agents/release-planner/agent.js");
  readonly "typed-handler": typeof import("../agents/typed-handler/agent.js");
};
