// Generated by Glove Foundry. Do not edit.
export type FoundryRoutes = {
  readonly "jax-redline": typeof import("../agents/jax-redline/agent.js");
  readonly "kenji-ghost": typeof import("../agents/kenji-ghost/agent.js");
  readonly "maya-nitro": typeof import("../agents/maya-nitro/agent.js");
};
