// Generated by Glove Foundry. Do not edit.
export type FoundryRoutes = {
  readonly "briefing-line": typeof import("../agents/briefing-line/agent.js");
  readonly "campaign-orchestrator": typeof import("../agents/campaign-orchestrator/agent.js");
  readonly "critic": typeof import("../agents/critic/agent.js");
  readonly "lead": typeof import("../agents/lead/agent.js");
  readonly "maker": typeof import("../agents/maker/agent.js");
  readonly "scout": typeof import("../agents/scout/agent.js");
  readonly "strategist": typeof import("../agents/strategist/agent.js");
};
