import { CodeBlock } from "@/components/code-block";
import { ProvenanceCanvas } from "@/components/provenance-canvas";
import { gallery } from "@/lib/gallery-data";

export const metadata = {
  title: "Image Gallery — worked examples",
  description:
    "Every image on this page was generated by glove-image, with its prompt, pipeline trace and cost recorded. A worked SS26 campaign: identity consistency, catalog matrices, recipe replay, edits and style swaps.",
};

type Shot = (typeof gallery.shots)[number];

const shotsIn = (set: string): Shot[] => gallery.shots.filter((s) => s.set === set);
const shot = (slug: string): Shot | undefined => gallery.shots.find((s) => s.slug === slug);

function Grid({ items, columns }: { items: readonly Shot[]; columns?: boolean }) {
  return (
    <div className={columns ? "gallery-pair" : "gallery-grid"}>
      {items.map((s) => (
        <figure key={s.slug} className="gallery-item">
          <img
            src={`/image-gallery/${s.file}`}
            alt={`${s.title} — ${s.intent}`}
            width={s.width}
            height={s.height}
            loading="lazy"
          />
          <figcaption className="gallery-meta">
            <span className="gallery-cost">${s.costUsd.toFixed(4)}</span>
            <strong>{s.title}</strong>
            <span>{s.note ?? s.intent}</span>
          </figcaption>
        </figure>
      ))}
    </div>
  );
}

export default async function GalleryPage() {
  const consistency = shotsIn("consistency");
  const matrix = shotsIn("matrix");
  const multi = shotsIn("multi");
  const regenerate = shotsIn("regenerate");
  const edit = shotsIn("edit");
  const style = shotsIn("style");
  const inventory = shotsIn("inventory");

  const hero = shot("consistency-kilimani-rooftop") ?? gallery.shots[0]!;
  const heroChars = gallery.characters.filter((c) => hero.characters.includes(c.name));
  const heroScene = gallery.scenes.find((s) => s.name === hero.scene);

  const total = gallery.usage.total;

  return (
    <div className="docs-content">
      <h1>Image Gallery</h1>

      <p>
        Every image on this page was produced by <code>glove-image</code> in a
        single scripted run — no hand-picking, no retries, no touch-ups. The
        prompt, the pipeline trace and the dollar cost under each one are read
        back from that image&apos;s recorded <code>Recipe</code>, so what you
        see is what actually happened.
      </p>

      <p>
        The brief: a fictional Nairobi accessories label shooting an SS26
        campaign. Two inventory items, one model, five locations. It is the
        shape of work a product stylist does by hand, and it is where a single{" "}
        <code>generate_image</code> tool stops being enough.
      </p>

      <div className="gallery-legend">
        <span>
          <i style={{ background: "var(--pc-character)" }} /> character
        </span>
        <span>
          <i style={{ background: "var(--pc-scene)" }} /> scene
        </span>
        <span>
          <i style={{ background: "var(--pc-style)" }} /> style directive
        </span>
        <span>
          <i style={{ background: "var(--pc-stage)" }} /> pipeline stage
        </span>
        <span>
          <i style={{ background: "var(--pc-prompt)" }} /> final prompt
        </span>
        <span>
          {gallery.shots.length} images · ${(total.cost_usd ?? 0).toFixed(2)} total
        </span>
      </div>

      {/* ---------------------------------------------------------------- */}
      <h2 id="canvas">How one image was made</h2>

      <p>
        Start with the mechanism. Nothing below is a diagram someone drew — it
        is one asset&apos;s lineage, rendered. Library definitions on the left
        feed the pipeline stages in the middle; the last stage hands a finished
        prompt to the image model on the right.
      </p>

      <ProvenanceCanvas
        data={{
          characters: heroChars.map((c) => ({
            name: c.name,
            display_name: c.display_name,
            appearance: c.appearance,
          })),
          scene: heroScene ? { label: heroScene.label, setting: heroScene.setting } : undefined,
          houseStyle: gallery.houseStyle,
          trace: [...hero.trace],
          finalPrompt: hero.finalPrompt,
          image: { file: hero.file, title: hero.title },
          costUsd: hero.costUsd,
        }}
      />

      <p>
        The thing to notice is where the words come from. The agent supplied one
        line of intent — <em>&ldquo;{hero.intent}&rdquo;</em> — and everything
        else was spliced in from the library by the pipeline. The character
        paragraph is copied <strong>verbatim</strong>, which is the entire
        mechanism behind consistency: the model is not remembering Amara between
        turns, it is being told about her identically every single time.
      </p>

      <div className="gallery-note">
        The trailing <code>fit-to-model</code> stage is the adapter contract
        being enforced. This model has no negative-prompt slot, so the
        accumulated negatives were folded into the prompt as an{" "}
        <code>Avoid:</code> clause and the change was written into the trace —
        the agent is told what was altered rather than silently getting
        something else.
      </div>

      {/* ---------------------------------------------------------------- */}
      <h2 id="inventory">The inventory</h2>

      <p>
        A shoot starts from the client&apos;s product photos. Here they are
        generated as stand-ins, but in a real workflow they would be imported
        with <code>glove_image_import</code> and pinned to a character as its
        identity reference — which is what keeps the bag the same bag downstream.
      </p>

      <Grid items={inventory} columns />

      <CodeBlock
        filename="library.ts"
        language="typescript"
        code={`// A product is a character too — a durable visual identity with
// reference images. Define it once; every later shot re-splices it.
glove_image_character_save({
  name: "kiondo-tote",
  appearance:
    "a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of " +
    "burnt-orange and black geometric pattern, tan leather handles and trim",
  ref_images: [{ asset: "img_...", label: "packshot" }],
})`}
      />

      {/* ---------------------------------------------------------------- */}
      <h2 id="consistency">One model, one product, five locations</h2>

      <p>
        The same two characters against five different scenes. Only the{" "}
        <code>scene</code> argument changes between these calls — the model and
        the bag are never re-described.
      </p>

      <Grid items={consistency} />

      <CodeBlock
        filename="shoot.ts"
        language="typescript"
        code={`for (const scene of ["kilimani-rooftop", "karura-forest", "maasai-market",
                     "nairobi-street", "nairobi-national-park"]) {
  await glove_image_generate({
    intent: "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
    characters: ["amara", "kiondo-tote"],
    scene,
  });
}`}
      />

      <p>
        Look at the gold hoops, the cream linen, the tan sandals, and the
        burnt-orange band on the bag across all five frames. That is not luck
        and it is not a seed — it is the same sentences arriving at the model
        five times.
      </p>

      {/* ---------------------------------------------------------------- */}
      <h2 id="matrix">The matrix collapses</h2>

      <p>
        Add a second inventory item and the whole grid comes for free — it is a
        loop over two lists, not <em>n×m</em> prompt-writing sessions.
      </p>

      <Grid items={matrix} />

      <p>
        And because characters compose, both products can share a frame without
        either drifting:
      </p>

      <Grid items={multi} columns />

      {/* ---------------------------------------------------------------- */}
      <h2 id="replay">Replaying a recipe</h2>

      <p>
        Every generated asset stores how it was made. &ldquo;Same shot, but at
        dusk&rdquo; is therefore one call against the original —{" "}
        <code>glove_image_regenerate</code> replays the recorded characters,
        scene, style and params through the <em>current</em> pipeline, with the
        tweak appended to the original intent.
      </p>

      <Grid items={regenerate} columns />

      <CodeBlock
        filename="revision.ts"
        language="typescript"
        code={`glove_image_regenerate({ asset: "img_...", tweak: "at dusk, city lights just coming on" })`}
      />

      <p>
        The practical consequence is that a client revision costs one line
        rather than a reconstruction of the original brief — and if a
        character&apos;s definition has been corrected in the meantime, the
        replay picks that up automatically.
      </p>

      {/* ---------------------------------------------------------------- */}
      <h2 id="edit">Editing without losing the frame</h2>

      <p>
        A colourway change is not a regeneration — it is an edit against the
        existing image, which records its <code>parent</code> so any frame&apos;s
        ancestry stays recoverable.
      </p>

      <Grid
        items={[shot("consistency-kilimani-rooftop"), ...edit].filter(Boolean) as Shot[]}
        columns
      />

      {/* ---------------------------------------------------------------- */}
      <h2 id="style">One line changes the whole look</h2>

      <p>
        Identical intent, identical characters, identical scene. The only
        difference is the <code>styleDirective</code> in the pipeline — which is
        how a single catalog gets re-shot for a different channel without
        rewriting a single prompt.
      </p>

      <Grid items={style} />

      <CodeBlock
        filename="pipeline.ts"
        language="typescript"
        code={`pipeline: [
  expandCharacters(),
  expandScenes(),
  styleDirective("shot on grainy 35mm film, muted kodak portra palette, soft halation"),
]`}
      />

      {/* ---------------------------------------------------------------- */}
      <h2 id="cost">What the whole page cost</h2>

      <p>
        Spend is metered on every model-touching call and attributed by source,
        so a shoot can be priced instead of estimated.
      </p>

      <table>
        <thead>
          <tr>
            <th>Source</th>
            <th>Requests</th>
            <th>Tokens in → out</th>
            <th>Cost</th>
          </tr>
        </thead>
        <tbody>
          {Object.entries(gallery.usage.by_source).map(([source, u]) => (
            <tr key={source}>
              <td>
                <code>{source}</code>
              </td>
              <td>{u.requests}</td>
              <td>
                {u.tokens_in.toLocaleString()} → {u.tokens_out.toLocaleString()}
              </td>
              <td>{u.cost_usd !== undefined ? `$${u.cost_usd.toFixed(4)}` : "—"}</td>
            </tr>
          ))}
          <tr>
            <td>
              <strong>total</strong>
            </td>
            <td>
              <strong>{total.requests}</strong>
            </td>
            <td>
              <strong>
                {total.tokens_in.toLocaleString()} → {total.tokens_out.toLocaleString()}
              </strong>
            </td>
            <td>
              <strong>${(total.cost_usd ?? 0).toFixed(4)}</strong>
            </td>
          </tr>
        </tbody>
      </table>

      <p>
        {gallery.shots.length} images for ${(total.cost_usd ?? 0).toFixed(2)}. The
        agent can read the same figures mid-conversation with{" "}
        <code>glove_image_usage</code>, and a host can stream them into billing
        through the <code>onUsage</code> callback.
      </p>

      <div className="gallery-note">
        <strong>Where this stops working.</strong> These are generative
        approximations, not photographs of real stock. Woven, textile and craft
        goods hold up well; a product carrying an exact logo, a precise
        colourway or fine hardware detail will not reproduce faithfully, even
        with a packshot pinned as its identity reference. For those, treat the
        output as styling reference rather than catalog-final.
      </div>

      <p>
        The full design is in the <a href="/docs/image">image workflows guide</a>
        , and <code>examples/image-studio</code> in the repository is a runnable
        agent that produces work like this from plain conversation.
      </p>
    </div>
  );
}
