import { mkdir, writeFile } from "node:fs/promises";
import { dirname, relative, resolve, sep } from "node:path";
import type { DiscoveredAgent, FoundryManifest } from "./discovery.js";

function moduleSpecifier(fromFile: string, targetFile: string): string {
  let specifier = relative(dirname(fromFile), targetFile).split(sep).join("/");
  if (!specifier.startsWith(".")) specifier = `./${specifier}`;
  return specifier.replace(/\.(?:tsx?|mts|mjs|js)$/, ".js");
}

export async function writeGeneratedTypes(options: {
  rootDir: string;
  agents: readonly DiscoveredAgent[];
  manifest: FoundryManifest;
}): Promise<{ routesFile: string; manifestFile: string }> {
  const generatedDir = resolve(options.rootDir, ".foundry");
  const routesFile = resolve(generatedDir, "routes.d.ts");
  const manifestFile = resolve(generatedDir, "manifest.json");
  await mkdir(generatedDir, { recursive: true });

  const routes = options.agents
    .map(
      ({ route, filePath }) =>
        `  readonly ${JSON.stringify(route)}: typeof import(${JSON.stringify(moduleSpecifier(routesFile, filePath))});`,
    )
    .join("\n");
  const source = `// Generated by Glove Foundry. Do not edit.\n` +
    `export type FoundryRoutes = {\n${routes}\n};\n`;
  await writeFile(routesFile, source, "utf8");
  await writeFile(manifestFile, `${JSON.stringify(options.manifest, null, 2)}\n`, "utf8");
  return { routesFile, manifestFile };
}
