export const DASHBOARD_STYLES = String.raw`
@import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,300;0,400;0,500;0,600;1,400&family=JetBrains+Mono:wght@400;500&display=swap');
:root{
  --bg:#080B0A;--bg-elevated:#0F1613;--bg-surface:#141D18;--bg-surface-2:#19241F;
  --border:#243029;--border-subtle:#18211C;--border-strong:#32453B;
  --text-primary:#E7EEEA;--text-secondary:#93A399;--text-tertiary:#5C6F64;
  --accent:#9ED4B8;--accent-soft:#7BBFA0;--accent-strong:#BEE7D0;
  --accent-dim:rgba(158,212,184,.08);--accent-glow:rgba(158,212,184,.045);--accent-line:rgba(158,212,184,.16);
  --interface:#E4B879;--network:#83B3E2;--deploy:#B8A7E8;--media:#E29BA8;
  --success:#8CC494;--warn:#E4B879;--danger:#E29BA8;
  --sans:'DM Sans',-apple-system,BlinkMacSystemFont,sans-serif;--mono:'JetBrains Mono',monospace;
  --sidebar:248px;--radius:10px;--radius-lg:14px;--shadow:0 24px 64px rgba(0,0,0,.34);
  font-family:var(--sans);color:var(--text-primary);background:var(--bg);color-scheme:dark;
}
*{box-sizing:border-box}html,body{margin:0;min-height:100%;background:var(--bg)}html{scroll-behavior:smooth}body{font-family:var(--sans);color:var(--text-primary);-webkit-font-smoothing:antialiased;overflow-x:hidden}
body:before{content:"";position:fixed;inset:0 0 auto 0;height:100vh;background:radial-gradient(60% 40% at 55% -5%,rgba(158,212,184,.06),transparent 70%);pointer-events:none;z-index:0}
button,input,textarea,select{font:inherit;color:inherit}button,a{touch-action:manipulation}button:focus-visible,a:focus-visible,input:focus-visible,textarea:focus-visible,select:focus-visible{outline:2px solid var(--accent-soft);outline-offset:2px;border-radius:5px}
::selection{background:rgba(158,212,184,.22);color:var(--text-primary)}.mono{font-family:var(--mono)}.muted{color:var(--text-secondary)}.hidden{display:none!important}
.icon{display:block;width:1em;height:1em;flex:0 0 auto;fill:currentColor}.icon-button{padding:8px;aspect-ratio:1}.icon-button .icon{width:17px;height:17px}
.app{min-height:100vh;position:relative;z-index:1}.sidebar{position:fixed;inset:0 auto 0 0;width:var(--sidebar);background:rgba(8,11,10,.92);backdrop-filter:blur(20px) saturate(140%);border-right:1px solid var(--border-subtle);z-index:20;display:flex;flex-direction:column}
.brand{height:72px;display:flex;align-items:center;gap:11px;padding:0 20px;border-bottom:1px solid var(--border-subtle);color:inherit;text-decoration:none}.brand-mark{width:26px;height:26px;color:var(--accent);filter:drop-shadow(0 3px 12px rgba(158,212,184,.2));transition:transform .25s ease}.brand:hover .brand-mark{transform:rotate(-7deg) scale(1.05)}.brand strong{display:block;font-size:14px;font-weight:600;letter-spacing:-.015em}.brand small{display:block;color:var(--text-tertiary);font:9px/1.4 var(--mono);text-transform:uppercase;letter-spacing:.13em;margin-top:3px}
.nav{padding:20px 12px}.nav-label{padding:0 11px 9px;color:var(--text-tertiary);font:9px var(--mono);text-transform:uppercase;letter-spacing:.15em}.nav a{position:relative;color:var(--text-secondary);text-decoration:none;display:flex;align-items:center;gap:11px;padding:9px 11px;border-radius:7px;margin:2px 0;font-size:13px;transition:color .18s,background .18s}.nav a:hover{background:var(--accent-glow);color:var(--text-primary)}.nav a.active{background:var(--accent-dim);color:var(--accent)}.nav a.active:before{content:"";position:absolute;left:-12px;width:2px;height:22px;background:var(--accent)}.nav-icon{width:18px;height:18px;color:var(--text-tertiary);display:grid;place-items:center}.nav-icon svg{width:17px;height:17px;fill:currentColor}.nav a.active .nav-icon{color:var(--accent)}
.sidebar-foot{margin-top:auto;padding:18px;border-top:1px solid var(--border-subtle)}.runtime-state{display:flex;align-items:center;gap:9px;font-size:11px;color:var(--text-secondary)}.runtime-state i{width:7px;height:7px;border-radius:50%;background:var(--success);box-shadow:0 0 8px rgba(140,196,148,.55)}.runtime-state.bad i{background:var(--danger)}.shortcut{margin-top:12px;width:100%;border:1px solid var(--border);background:var(--bg-elevated);color:var(--text-secondary);border-radius:7px;padding:8px 10px;text-align:left;font-size:11px;cursor:pointer;display:flex;align-items:center;justify-content:space-between}.shortcut:hover{border-color:var(--border-strong);color:var(--text-primary)}.shortcut-label{display:flex;align-items:center;gap:7px}.shortcut-label .icon{width:14px;height:14px}.shortcut kbd{color:var(--text-tertiary);font:9px var(--mono);border:0;background:transparent;padding:0}
.main{margin-left:var(--sidebar);min-height:100vh}.topbar{height:72px;background:rgba(8,11,10,.72);backdrop-filter:blur(20px) saturate(140%);border-bottom:1px solid var(--border-subtle);display:flex;align-items:center;padding:0 32px;position:sticky;top:0;z-index:10}.breadcrumbs{display:flex;align-items:center;gap:8px;font:11px var(--mono);color:var(--text-tertiary)}.breadcrumbs a{color:var(--text-tertiary);text-decoration:none}.breadcrumbs a:hover{color:var(--accent)}.crumb-separator{display:grid;place-items:center;color:var(--text-tertiary)}.crumb-separator .icon{width:10px;height:10px}.top-actions{margin-left:auto;display:flex;align-items:center;gap:9px}.live-chip{display:flex;align-items:center;gap:7px;border:1px solid var(--border);background:var(--bg-elevated);padding:8px 10px;border-radius:7px;font:9px var(--mono);text-transform:uppercase;letter-spacing:.07em;color:var(--text-secondary)}.live-chip i{width:6px;height:6px;border-radius:50%;background:var(--success);box-shadow:0 0 8px rgba(140,196,148,.45)}
.button{border:1px solid var(--border);background:var(--bg-elevated);color:var(--text-secondary);border-radius:7px;padding:9px 13px;font-weight:500;font-size:12px;cursor:pointer;text-decoration:none;display:inline-flex;align-items:center;justify-content:center;gap:7px;transition:border-color .18s,background .18s,color .18s,transform .18s}.button>.icon{width:15px;height:15px}.button:hover{border-color:var(--border-strong);background:var(--bg-surface);color:var(--text-primary)}.button.primary{border-color:var(--accent);background:var(--accent);color:var(--bg);font-weight:600;box-shadow:0 2px 18px rgba(158,212,184,.12)}.button.primary:hover{background:var(--accent-strong);transform:translateY(-1px)}.mobile-toggle{display:none}.content{max-width:1480px;margin:0 auto;padding:36px 36px 72px;position:relative}
.content:before{content:"";position:absolute;inset:0;z-index:-1;pointer-events:none;background-image:linear-gradient(var(--border-subtle) 1px,transparent 1px),linear-gradient(90deg,var(--border-subtle) 1px,transparent 1px);background-size:56px 56px;mask-image:linear-gradient(to bottom,rgba(0,0,0,.25),transparent 300px);opacity:.34}
.page-head{display:flex;align-items:flex-end;gap:24px;margin-bottom:28px}.eyebrow{display:flex;align-items:center;gap:8px;font:10px var(--mono);color:var(--accent-soft);text-transform:uppercase;letter-spacing:.14em;margin-bottom:12px}.eyebrow:before{content:"";width:18px;height:1px;background:var(--accent-line)}.page-head h1{font-size:34px;font-weight:400;line-height:1.08;letter-spacing:-.035em;margin:0}.page-head p{margin:9px 0 0;color:var(--text-secondary);max-width:690px;font-size:14px;font-weight:300;line-height:1.6}.page-head .actions{margin-left:auto;display:flex;gap:8px;align-items:center}.page-rule{width:42px;height:2px;background:var(--accent);margin-bottom:16px}
.grid{display:grid;gap:14px}.cols-4{grid-template-columns:repeat(4,1fr)}.cols-3{grid-template-columns:repeat(3,1fr)}.cols-2{grid-template-columns:repeat(2,1fr)}.span-2{grid-column:span 2}.card{background:rgba(15,22,19,.92);border:1px solid var(--border-subtle);border-radius:var(--radius);min-width:0;margin-bottom:14px;overflow:hidden}.card-head{padding:14px 16px;border-bottom:1px solid var(--border-subtle);display:flex;align-items:center;gap:12px;background:rgba(20,29,24,.3)}.card-head h2{font-size:13px;font-weight:500;margin:0}.card-head .meta{margin-left:auto;color:var(--text-tertiary);font:9px var(--mono)}.card-body{padding:16px}.metric{padding:18px;min-height:124px;margin-bottom:0}.metric label{display:block;color:var(--text-tertiary);font:9px var(--mono);text-transform:uppercase;letter-spacing:.12em}.metric strong{display:block;font-size:30px;font-weight:400;letter-spacing:-.035em;margin-top:15px}.metric small{display:block;color:var(--text-secondary);font-size:11px;font-weight:300;margin-top:6px}.metric.accent{border-top:2px solid var(--accent)}
.table-wrap{overflow:auto}.table{width:100%;border-collapse:collapse;min-width:650px}.table th{padding:11px 15px;text-align:left;color:var(--text-tertiary);font:9px var(--mono);text-transform:uppercase;letter-spacing:.1em;border-bottom:1px solid var(--border-subtle);white-space:nowrap}.table td{padding:13px 15px;border-bottom:1px solid var(--border-subtle);font-size:12px;vertical-align:top}.table tr:last-child td{border-bottom:0}.table tbody tr.clickable{cursor:pointer}.table tbody tr.clickable:hover{background:var(--accent-glow)}.primary-cell{font-weight:500;color:var(--text-primary)}.secondary{display:block;color:var(--text-tertiary);font:9px/1.55 var(--mono);margin-top:4px;overflow-wrap:anywhere}
.status{display:inline-flex;align-items:center;gap:6px;border-radius:999px;padding:4px 8px;background:var(--bg-surface-2);color:var(--text-secondary);font:8px var(--mono);text-transform:uppercase;letter-spacing:.06em;white-space:nowrap;border:1px solid var(--border)}.status:before{content:"";width:5px;height:5px;border-radius:50%;background:var(--text-tertiary)}.status.completed,.status.connected,.status.active,.status.enabled,.status.resolved{background:rgba(140,196,148,.08);color:var(--success);border-color:rgba(140,196,148,.18)}.status.completed:before,.status.connected:before,.status.active:before,.status.enabled:before,.status.resolved:before{background:var(--success)}.status.running,.status.pending,.status.connecting,.status.reconnecting,.status.in-progress{background:rgba(131,179,226,.08);color:var(--network);border-color:rgba(131,179,226,.18)}.status.running:before,.status.pending:before,.status.connecting:before,.status.reconnecting:before,.status.in-progress:before{background:var(--network)}.status.paused{background:rgba(226,187,131,.08);color:var(--warning);border-color:rgba(226,187,131,.18)}.status.paused:before{background:var(--warning)}.status.failed,.status.cancelled,.status.disconnected,.status.dismissed{background:rgba(226,155,168,.08);color:var(--danger);border-color:rgba(226,155,168,.18)}.status.failed:before,.status.cancelled:before,.status.disconnected:before,.status.dismissed:before{background:var(--danger)}
.tag{display:inline-block;border:1px solid var(--border);border-radius:4px;padding:3px 6px;font:8px var(--mono);color:var(--text-secondary);margin:2px 4px 2px 0;background:var(--bg-surface)}.link{color:var(--accent);text-decoration:none;font-weight:500}.link:hover{text-decoration:underline;text-decoration-color:var(--accent-line)}.inline-icon{display:inline-flex;align-items:center;gap:5px}.inline-icon .icon{width:12px;height:12px}.empty{padding:38px 22px;text-align:center;color:var(--text-secondary);font-size:12px;line-height:1.6}.empty strong{display:block;color:var(--text-primary);font-size:14px;font-weight:500;margin-bottom:5px}.filters{display:flex;gap:8px;margin-bottom:14px}.filters input,.filters select{background:var(--bg-elevated);border:1px solid var(--border);border-radius:7px;padding:10px 12px;font-size:12px}.filters input{min-width:280px}
.definition-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin-bottom:16px}.definition-card{display:block;color:inherit;text-decoration:none;background:var(--bg-elevated);border:1px solid var(--border-subtle);border-radius:var(--radius-lg);padding:19px;min-height:196px;position:relative;overflow:hidden;transition:transform .2s ease,border-color .2s ease,background .2s}.definition-card:before{content:"";position:absolute;inset:0;opacity:0;background:radial-gradient(110% 80% at 100% 0%,var(--accent-dim),transparent 60%);transition:opacity .2s}.definition-card:hover{transform:translateY(-2px);border-color:var(--accent-line);background:var(--bg-surface)}.definition-card:hover:before{opacity:1}.definition-icon{width:31px;height:31px;display:grid;place-items:center;border:1px solid var(--accent-line);border-radius:8px;color:var(--accent);background:var(--accent-dim);margin-bottom:15px;position:relative}.definition-icon .icon{width:17px;height:17px}.definition-open{position:absolute;right:17px;top:17px;color:var(--text-tertiary);transition:color .18s,transform .18s}.definition-open .icon{width:14px;height:14px}.definition-card:hover .definition-open{color:var(--accent);transform:translate(1px,-1px)}.definition-card h3{margin:0;font-size:17px;font-weight:500;position:relative}.definition-card p{color:var(--text-secondary);font-size:12px;font-weight:300;line-height:1.6;margin:9px 0 18px;position:relative}.definition-meta{position:absolute;left:19px;right:19px;bottom:17px;display:flex;justify-content:space-between;align-items:end}.definition-meta b{font:9px var(--mono);color:var(--accent-soft)}
.cap-list{display:flex;flex-wrap:wrap;gap:6px}.cap{border:1px solid var(--border);background:var(--bg-surface);border-radius:5px;padding:7px 9px;font:9px var(--mono);margin-bottom:6px;color:var(--text-secondary)}.detail-strip{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));border:1px solid var(--border-subtle);border-radius:var(--radius);background:var(--bg-elevated);margin-bottom:14px;overflow:hidden}.detail-strip>div{padding:15px;border-right:1px solid var(--border-subtle);min-width:0}.detail-strip>div:last-child{border-right:0}.detail-strip label{display:block;color:var(--text-tertiary);font:8px var(--mono);text-transform:uppercase;letter-spacing:.1em}.detail-strip strong{display:block;margin-top:8px;font-size:12px;font-weight:500;overflow-wrap:anywhere}.json{margin:0;background:#070A09;color:var(--text-secondary);border:1px solid var(--border-subtle);border-radius:7px;padding:14px;font:9px/1.65 var(--mono);white-space:pre-wrap;overflow:auto;max-height:360px}.summary-box{font-size:12px;line-height:1.65;overflow-wrap:anywhere}.summary-box dl{display:grid;grid-template-columns:130px 1fr;gap:9px 14px;margin:0}.summary-box dt{color:var(--text-tertiary);font:8px var(--mono);text-transform:uppercase;letter-spacing:.08em}.summary-box dd{margin:0;color:var(--text-secondary)}
.run-spine{position:relative;padding:4px 0}.run-spine:before{content:"";position:absolute;left:19px;top:14px;bottom:14px;width:1px;background:var(--border)}.phase{position:relative;display:grid;grid-template-columns:40px 1fr auto;gap:12px;padding:11px 4px}.phase-dot{width:12px;height:12px;border-radius:50%;background:var(--bg-elevated);border:2px solid var(--text-tertiary);margin:2px 0 0 13px;z-index:1}.phase.complete .phase-dot{border-color:var(--success);box-shadow:0 0 8px rgba(140,196,148,.2)}.phase.active .phase-dot{border-color:var(--network);box-shadow:0 0 0 5px rgba(131,179,226,.09)}.phase.error .phase-dot{border-color:var(--danger)}.phase strong{font-size:12px;font-weight:500}.phase p{margin:4px 0 0;color:var(--text-secondary);font-size:11px;font-weight:300;line-height:1.5}.phase time{font:8px var(--mono);color:var(--text-tertiary)}
.event-row{border-top:1px solid var(--border-subtle)}.event-toggle{width:100%;border:0;background:transparent;padding:12px 15px;display:grid;grid-template-columns:82px 110px minmax(0,1fr) auto;gap:11px;text-align:left;align-items:center;cursor:pointer}.event-toggle:hover,.event-row.open .event-toggle{background:var(--accent-glow)}.event-time,.event-category{font:8px var(--mono);color:var(--text-tertiary)}.event-type{font:9px var(--mono);overflow:hidden;text-overflow:ellipsis}.event-detail{display:none;padding:0 15px 14px}.event-row.open .event-detail{display:block}.trace-note{border-left:2px solid var(--accent);padding:10px 12px;background:var(--accent-dim);font-size:11px;line-height:1.5;color:var(--text-secondary);margin-bottom:14px}
.workspace-tabs{display:flex;gap:2px;border-bottom:1px solid var(--border-subtle);margin:20px 0 14px}.workspace-tabs button{border:0;background:transparent;padding:11px 13px;color:var(--text-secondary);font-size:11px;cursor:pointer;border-bottom:2px solid transparent}.workspace-tabs button.active{color:var(--accent);border-color:var(--accent);font-weight:500}.kv{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.kv-item{border:1px solid var(--border-subtle);border-radius:7px;padding:13px;background:var(--bg-surface)}.kv-item strong{font:10px var(--mono)}.kv-item small{display:block;color:var(--text-tertiary);margin-top:6px}.kv-value{margin-top:12px;color:var(--text-secondary);font-size:11px;line-height:1.5;overflow-wrap:anywhere}.callout{border:1px solid var(--accent-line);background:var(--accent-glow);border-radius:8px;padding:15px 17px;display:flex;align-items:flex-start;gap:12px;margin-bottom:14px}.callout b{font-size:12px;font-weight:500}.callout p{margin:4px 0 0;color:var(--text-secondary);font-size:11px;line-height:1.5}.callout .symbol{width:31px;height:31px;display:grid;place-items:center;flex:0 0 auto;border:1px solid var(--accent-line);border-radius:7px;color:var(--accent);background:var(--accent-dim)}.callout .symbol .icon{width:16px;height:16px}
.drawer-backdrop{position:fixed;inset:0;background:rgba(0,0,0,.62);backdrop-filter:blur(3px);z-index:40;display:none}.drawer-backdrop.open{display:block}.drawer{position:absolute;right:0;top:0;bottom:0;width:min(520px,100%);background:var(--bg-elevated);border-left:1px solid var(--border);box-shadow:-20px 0 60px rgba(0,0,0,.35);padding:26px;overflow:auto}.drawer-head{display:flex;align-items:flex-start;margin-bottom:28px}.drawer h2{margin:0;font-size:23px;font-weight:400;letter-spacing:-.025em}.drawer-head button{margin-left:auto;border:0;background:transparent;color:var(--text-secondary);cursor:pointer}.drawer-head button:hover{color:var(--text-primary);background:var(--bg-surface)}.field{margin-bottom:17px}.field label{display:block;font:8px var(--mono);text-transform:uppercase;letter-spacing:.12em;color:var(--text-tertiary);margin-bottom:7px}.field input,.field textarea,.field select{width:100%;border:1px solid var(--border);background:var(--bg);border-radius:7px;padding:11px 12px;font-size:12px}.field textarea{min-height:120px;resize:vertical}.form-error{background:rgba(226,155,168,.08);color:var(--danger);border:1px solid rgba(226,155,168,.18);border-radius:7px;padding:10px 12px;font-size:11px;margin-bottom:13px}.drawer-actions{display:flex;justify-content:flex-end;gap:8px;margin-top:22px}
.search-modal{position:fixed;inset:0;background:rgba(0,0,0,.64);backdrop-filter:blur(4px);z-index:50;display:none;padding:12vh 20px}.search-modal.open{display:block}.search-box{max-width:650px;margin:auto;background:var(--bg-elevated);border:1px solid var(--border);border-radius:10px;box-shadow:var(--shadow);overflow:hidden}.search-input-wrap{display:flex;align-items:center;gap:12px;padding:0 20px;border-bottom:1px solid var(--border);color:var(--text-tertiary)}.search-input-wrap>.icon{width:19px;height:19px}.search-box input{width:100%;border:0;background:var(--bg-elevated);padding:18px 0;font-size:15px}.search-results{max-height:420px;overflow:auto;padding:8px}.search-result{display:block;padding:11px 12px;border-radius:6px;text-decoration:none;color:inherit}.search-result:hover{background:var(--accent-glow)}.search-result strong{font-size:12px;font-weight:500}.search-result small{display:block;color:var(--text-tertiary);margin-top:3px}.toast{position:fixed;right:24px;bottom:24px;background:var(--accent);color:var(--bg);border-radius:7px;padding:12px 15px;font-size:11px;font-weight:600;box-shadow:var(--shadow);z-index:60;transform:translateY(20px);opacity:0;pointer-events:none;transition:.2s}.toast.show{transform:none;opacity:1}
@media(max-width:1100px){.cols-4{grid-template-columns:repeat(2,1fr)}.definition-grid{grid-template-columns:repeat(2,1fr)}.cols-3{grid-template-columns:1fr 1fr}}
@media(max-width:760px){:root{--sidebar:0px}.sidebar{transform:translateX(-248px);width:248px;transition:transform .2s ease}.sidebar.open{transform:none}.mobile-toggle{display:inline-flex}.topbar{padding:0 16px}.live-chip{display:none}.content{padding:24px 16px 55px}.page-head{display:block}.page-head .actions{margin:18px 0 0}.cols-4,.cols-3,.cols-2,.definition-grid,.kv{grid-template-columns:1fr}.span-2{grid-column:auto}.detail-strip{display:block}.detail-strip>div{border-right:0;border-bottom:1px solid var(--border-subtle)}.filters{flex-wrap:wrap}.filters input{min-width:100%;width:100%}.event-toggle{grid-template-columns:70px 90px 1fr}.event-toggle span:last-child{display:none}.top-actions .button.primary span{display:none}}

/* ---- Elapsed time and duration ---- */
.rel{color:var(--text-secondary);white-space:nowrap;font-variant-numeric:tabular-nums;cursor:help;border-bottom:1px dotted var(--border-strong)}
.dur{font-family:var(--mono);font-size:10px;color:var(--text-secondary);white-space:nowrap;font-variant-numeric:tabular-nums}
.dur.live{color:var(--accent);position:relative;padding-left:12px}
.dur.live:before{content:"";position:absolute;left:0;top:50%;transform:translateY(-50%);width:5px;height:5px;border-radius:50%;background:var(--accent);animation:pulse-dot 1.6s ease-in-out infinite}
@keyframes pulse-dot{0%,100%{opacity:1;box-shadow:0 0 0 0 var(--accent-line)}50%{opacity:.45;box-shadow:0 0 0 4px transparent}}
.attempts{font-family:var(--mono);font-size:10px;color:var(--text-tertiary);font-variant-numeric:tabular-nums}
.attempts.warn{color:var(--warn)}

/* ---- Copyable identifiers ---- */
.id-cell{display:inline-flex;align-items:center;gap:5px;min-width:0}
.id-cell .mono{font-family:var(--mono);font-size:11px;color:var(--text-primary);overflow:hidden;text-overflow:ellipsis}
.copy-btn{border:0;background:transparent;color:var(--text-tertiary);padding:3px;border-radius:5px;cursor:pointer;display:inline-flex;align-items:center;opacity:0;transition:opacity .14s,color .14s,background .14s}
.copy-btn .icon{width:12px;height:12px}
.copy-btn .copy-ok{display:none}
tr:hover .copy-btn,.id-cell:hover .copy-btn,.copy-btn:focus-visible{opacity:1}
.copy-btn:hover{color:var(--accent);background:var(--accent-dim)}
.copy-btn.copied{opacity:1;color:var(--success)}
.copy-btn.copied .icon{display:none}
.copy-btn.copied .copy-ok{display:block}
.button .icon{width:13px;height:13px}

/* ---- Filter toolbar ---- */
.toolbar{display:flex;align-items:center;gap:12px;flex-wrap:wrap;margin-bottom:14px}
.toolbar-right{display:flex;align-items:center;gap:8px;margin-left:auto;flex-wrap:wrap}
.segmented{display:inline-flex;background:var(--bg-elevated);border:1px solid var(--border-subtle);border-radius:8px;padding:3px;gap:2px;overflow:auto}
.segmented button{border:0;background:transparent;color:var(--text-secondary);font-size:11px;font-weight:500;padding:6px 10px;border-radius:6px;cursor:pointer;display:inline-flex;align-items:center;gap:6px;white-space:nowrap;transition:background .16s,color .16s}
.segmented button:hover{color:var(--text-primary)}
.segmented button.active{background:var(--bg-surface-2);color:var(--text-primary);box-shadow:inset 0 0 0 1px var(--border)}
.seg-count{font-family:var(--mono);font-size:9px;color:var(--text-tertiary);background:var(--bg);border-radius:20px;padding:2px 6px;font-variant-numeric:tabular-nums}
.segmented button.active .seg-count{color:var(--accent);background:var(--accent-dim)}
.search-field,.select-field{position:relative;display:inline-flex;align-items:center}
.search-field-icon,.select-field-icon{position:absolute;left:10px;display:flex;color:var(--text-tertiary);pointer-events:none}
.search-field-icon .icon,.select-field-icon .icon{width:13px;height:13px}
.search-field input,.select-field select{background:var(--bg-elevated);border:1px solid var(--border-subtle);border-radius:8px;padding:8px 12px 8px 30px;font-size:12px;color:var(--text-primary);min-width:150px}
.search-field input{min-width:230px}
.select-field select{appearance:none;cursor:pointer;padding-right:26px}
.search-field input::placeholder{color:var(--text-tertiary)}
.search-field input:focus,.select-field select:focus{border-color:var(--border-strong);outline:none}
.filter-note{display:flex;align-items:center;gap:12px;flex-wrap:wrap;font-size:11px;color:var(--text-secondary);background:var(--accent-glow);border:1px solid var(--accent-line);border-radius:8px;padding:9px 13px;margin-bottom:14px}
.filter-note .link{border:0;background:transparent;cursor:pointer;font-size:11px;padding:0;margin-left:auto}
.hint{font:10px var(--mono);color:var(--text-tertiary);margin:14px 0 0;letter-spacing:.03em}
.card-foot{padding:11px 15px;border-top:1px solid var(--border-subtle);font-size:11px}

/* ---- Row states and the keyboard cursor ---- */
.runs-table{min-width:820px}
tr.row-failed td:first-child{box-shadow:inset 2px 0 0 var(--danger)}
tr.row-live td:first-child{box-shadow:inset 2px 0 0 var(--accent)}
tr.cursor,.definition-card.cursor{outline:1px solid var(--accent-soft);outline-offset:-1px;background:var(--accent-glow)}

/* ---- Alerts ---- */
.alert{display:flex;gap:13px;align-items:flex-start;border-radius:var(--radius);padding:14px 16px;margin-bottom:16px;border:1px solid var(--border)}
.alert .symbol{display:flex;flex:0 0 auto;margin-top:1px}
.alert .symbol .icon{width:17px;height:17px}
.alert b{display:block;font-size:12px;font-weight:600;margin-bottom:3px}
.alert p{margin:0;font-size:12px;color:var(--text-secondary);line-height:1.55;word-break:break-word}
.alert.danger{background:rgba(226,155,168,.07);border-color:rgba(226,155,168,.26)}
.alert.danger .symbol{color:var(--danger)}
.alert.danger b{color:var(--danger)}
.alert.live{background:var(--accent-glow);border-color:var(--accent-line)}
.alert.live b{color:var(--accent)}
.pulse-dot{width:9px;height:9px;border-radius:50%;background:var(--accent);display:block;margin-top:4px;animation:pulse-dot 1.6s ease-in-out infinite}
.live-chip.pulse i{animation:live-ping .7s ease-out}
@keyframes live-ping{0%{transform:scale(1);opacity:1}45%{transform:scale(2.1);opacity:.45}100%{transform:scale(1);opacity:1}}

/* ---- Effect approvals. One warm decision rail breaks the cool runtime surface. ---- */
.approval-rail{position:relative;border:1px solid rgba(228,184,121,.28);border-left:3px solid var(--warn);border-radius:var(--radius);background:linear-gradient(100deg,rgba(228,184,121,.075),rgba(15,22,19,.96) 38%);margin-bottom:16px;overflow:hidden;box-shadow:0 16px 36px rgba(0,0,0,.16)}
.approval-rail>header{display:flex;align-items:flex-start;gap:20px;padding:16px 18px;border-bottom:1px solid rgba(228,184,121,.16)}
.approval-rail h2{margin:4px 0 0;font-size:16px;font-weight:500;letter-spacing:-.015em}.approval-rail header p{margin:5px 0 0;color:var(--text-secondary);font-size:11px;line-height:1.5}.approval-kicker{font:8px var(--mono);text-transform:uppercase;letter-spacing:.15em;color:var(--warn)}.approval-count{margin-left:auto;border:1px solid rgba(228,184,121,.24);border-radius:999px;padding:4px 8px;color:var(--warn);font:8px var(--mono);text-transform:uppercase;letter-spacing:.08em;white-space:nowrap}
.approval-list{display:grid}.approval-item{padding:16px 18px;border-top:1px solid var(--border-subtle)}.approval-item:first-child{border-top:0}.approval-context{display:flex;align-items:center;gap:10px;margin-bottom:10px}.approval-tool{font:10px var(--mono);color:var(--text-primary);background:rgba(228,184,121,.08);border:1px solid rgba(228,184,121,.18);border-radius:5px;padding:5px 8px}.approval-run{margin-left:auto;color:var(--text-secondary);font:9px var(--mono);text-decoration:none}.approval-run:hover{color:var(--warn)}
.approval-input{margin:0;max-height:220px;overflow:auto;white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid var(--border-subtle);border-radius:7px;background:#070A09;padding:12px;color:var(--text-secondary);font:9px/1.65 var(--mono)}.approval-foot{display:flex;align-items:center;gap:16px;margin-top:12px;color:var(--text-tertiary);font:9px var(--mono)}.approval-actions{display:flex;gap:8px;margin-left:auto}.button.approve{border-color:var(--warn);background:var(--warn);color:#14110A;font-weight:600}.button.approve:hover{border-color:#F0C98D;background:#F0C98D;transform:translateY(-1px)}.approval-actions button:disabled{opacity:.55;cursor:wait;transform:none}

/* ---- Event trace ---- */
.event-controls{display:flex;align-items:center;gap:12px;flex-wrap:wrap;padding:12px 15px;border-bottom:1px solid var(--border-subtle)}
.event-controls-right{display:flex;align-items:center;gap:12px;margin-left:auto;flex-wrap:wrap}
.event-controls-right .muted{font-size:11px}
.event-list{max-height:640px;overflow:auto}
.chips{display:flex;gap:5px;flex-wrap:wrap}
.chip{border:1px solid var(--border-subtle);background:var(--bg-elevated);color:var(--text-secondary);border-radius:20px;padding:5px 11px;font:9px var(--mono);text-transform:uppercase;letter-spacing:.07em;cursor:pointer;transition:border-color .16s,color .16s,background .16s}
.chip:hover{color:var(--text-primary);border-color:var(--border)}
.chip.active{background:var(--accent-dim);border-color:var(--accent-line);color:var(--accent)}
.event-toggle{grid-template-columns:74px 62px 104px minmax(0,1fr) auto!important}
.event-offset{color:var(--accent-soft);font-size:9px;font-variant-numeric:tabular-nums}
.event-caret{display:flex;color:var(--text-tertiary)}
.event-caret .icon{width:13px;height:13px;transition:transform .18s}
.event-row.open .event-caret .icon{transform:rotate(180deg)}
.event-detail-head{display:flex;align-items:center;gap:8px;padding:9px 15px 0}
.event-detail-head .copy-btn{opacity:1;margin-left:auto}

/* ---- Skeletons ---- */
.skeleton{padding:6px 0}
.skeleton-row{display:flex;align-items:center;gap:16px;padding:13px 15px;border-bottom:1px solid var(--border-subtle)}
.skeleton-row span{height:9px;border-radius:20px;background:linear-gradient(90deg,var(--bg-surface) 0%,var(--bg-surface-2) 50%,var(--bg-surface) 100%);background-size:200% 100%;animation:shimmer 1.5s linear infinite}
.skeleton-row span:last-child{margin-left:auto}
@keyframes shimmer{0%{background-position:200% 0}100%{background-position:-200% 0}}
.boot-skeleton{padding:32px}
.boot-skeleton p{font-size:12px;margin-top:18px}

/* ---- Run drawer ---- */
.drawer-hint{font-size:9px;color:var(--text-tertiary);margin-right:auto;letter-spacing:.06em}
.button.pending{opacity:.65;cursor:progress}
.button.danger{color:var(--danger);border-color:rgba(226,155,168,.3)}
.button.danger:hover{background:rgba(226,155,168,.09);border-color:var(--danger)}

/* ---- WebChat. A focused conversation surface backed by native Glove history. ---- */
.content.chat-content{max-width:none;height:calc(100vh - 72px);padding:0;overflow:hidden}
.content.chat-content:before{display:none}
.chat-shell{display:grid;grid-template-columns:290px minmax(0,1fr);height:100%;background:var(--bg)}
.session-rail{min-width:0;border-right:1px solid var(--border-subtle);background:rgba(15,22,19,.7);display:flex;flex-direction:column;overflow:hidden}
.session-head{height:76px;padding:18px;display:flex;align-items:center;border-bottom:1px solid var(--border-subtle)}
.session-head>div{min-width:0}.session-head .eyebrow{font-size:8px;margin:0 0 5px}.session-head h1{margin:0;font-size:18px;font-weight:500;letter-spacing:-.02em}.session-head .button{margin-left:auto;color:var(--accent);background:var(--accent-dim);border-color:var(--accent-line)}
.session-agent{padding:14px 15px 8px}.session-agent>span{display:block;margin-bottom:6px;color:var(--text-tertiary);font:8px var(--mono);text-transform:uppercase;letter-spacing:.1em}.session-agent select{width:100%;border:1px solid var(--border);background:var(--bg);border-radius:7px;padding:9px 10px;font-size:11px}
.session-search{position:relative;margin:4px 15px 10px;display:flex;align-items:center;color:var(--text-tertiary)}.session-search>.icon{position:absolute;left:10px;width:13px;height:13px}.session-search input{width:100%;border:1px solid var(--border-subtle);background:var(--bg);border-radius:7px;padding:9px 10px 9px 31px;font-size:11px}.session-search input::placeholder{color:var(--text-tertiary)}
.session-list{padding:2px 8px 18px;overflow:auto;min-height:0}.chat-session{position:relative;width:100%;border:1px solid transparent;background:transparent;color:var(--text-secondary);padding:11px 12px;border-radius:7px;text-align:left;cursor:pointer;margin:1px 0}.chat-session:hover{background:var(--accent-glow);color:var(--text-primary)}.chat-session.active{background:var(--accent-dim);border-color:var(--accent-line);color:var(--text-primary)}.chat-session.active:before{content:"";position:absolute;left:0;top:10px;bottom:10px;width:2px;background:var(--accent)}.chat-session span{display:block;font-size:12px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat-session small{display:block;margin-top:5px;color:var(--text-tertiary);font:8px var(--mono);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.conversation-pane{min-width:0;min-height:0;display:flex;flex-direction:column;background:radial-gradient(70% 38% at 50% 0%,var(--accent-glow),transparent 75%)}
.conversation-head{height:76px;flex:0 0 auto;border-bottom:1px solid var(--border-subtle);padding:14px 22px;display:flex;align-items:center;gap:20px;background:rgba(8,11,10,.5)}.conversation-head>div:first-child{min-width:0}.conversation-kicker{display:block;color:var(--accent-soft);font:8px var(--mono);text-transform:uppercase;letter-spacing:.1em;margin-bottom:5px}.conversation-head h2{margin:0;font-size:17px;font-weight:500;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.conversation-meta{margin-left:auto;display:flex;align-items:center;gap:10px;color:var(--text-tertiary);font:8px var(--mono);white-space:nowrap}.conversation-rename{border:0;background:transparent;color:var(--text-tertiary);padding:5px 7px;border-radius:5px;font:8px var(--mono);cursor:pointer}.conversation-rename:hover{color:var(--accent);background:var(--accent-dim)}
.chat-store-warning{flex:0 0 auto;border-bottom:1px solid rgba(228,184,121,.22);background:rgba(228,184,121,.07);color:var(--warn);padding:9px 20px;font-size:10px;text-align:center}
.message-scroll{flex:1;min-height:0;overflow:auto;padding:32px max(24px,calc((100% - 920px)/2)) 22px;scrollbar-gutter:stable}
.load-history{display:flex;align-items:center;justify-content:center;gap:10px;margin:-12px auto 24px}.load-history .button{font-size:10px}.load-history>span{color:var(--text-tertiary);font:8px var(--mono)}
.chat-message{display:flex;align-items:flex-start;gap:12px;margin:0 auto 24px;max-width:920px}.chat-message.user{flex-direction:row-reverse}.message-avatar{width:29px;height:29px;flex:0 0 auto;border:1px solid var(--border);border-radius:8px;background:var(--bg-surface);color:var(--text-secondary);display:grid;place-items:center;font:10px var(--mono)}.message-avatar .icon{width:16px;height:16px;color:var(--accent)}.chat-message.user .message-avatar{background:var(--accent);border-color:var(--accent);color:var(--bg);font-weight:700}
.message-body{min-width:0;max-width:min(780px,82%)}.message-body>header{display:flex;align-items:center;gap:8px;margin:0 2px 6px}.message-body>header strong{font-size:11px;font-weight:600}.message-body>header span{color:var(--text-tertiary);font:8px var(--mono);text-transform:uppercase}.chat-message.user .message-body>header{justify-content:flex-end}.message-text{white-space:pre-wrap;overflow-wrap:anywhere;border:1px solid var(--border-subtle);background:var(--bg-elevated);border-radius:4px 12px 12px 12px;padding:12px 14px;color:var(--text-primary);font-size:13px;font-weight:300;line-height:1.62}.chat-message.user .message-text{border-color:var(--accent-line);background:var(--accent-dim);border-radius:12px 4px 12px 12px}.chat-message.optimistic{opacity:.65}
.chat-message.tool .message-avatar .icon{color:var(--network)}.chat-message.tool .message-body>header strong{color:var(--network)}
.message-attachments{display:flex;flex-wrap:wrap;gap:7px;margin-top:8px}.message-attachments>span{display:grid;grid-template-columns:18px minmax(0,1fr);column-gap:7px;align-items:center;min-width:160px;border:1px solid var(--border);background:var(--bg-surface);border-radius:7px;padding:8px 10px}.message-attachments .icon{grid-row:1/3;color:var(--accent);width:16px;height:16px}.message-attachments b{font-size:10px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.message-attachments small{color:var(--text-tertiary);font:8px var(--mono)}
.message-tools{margin-top:7px;border:1px solid var(--border-subtle);border-radius:7px;background:#070A09;overflow:hidden}.message-tools summary{padding:8px 10px;color:var(--network);font:9px var(--mono);cursor:pointer}.message-tools pre{margin:0;border-top:1px solid var(--border-subtle);padding:10px;max-height:260px;overflow:auto;color:var(--text-secondary);white-space:pre-wrap;font:8px/1.55 var(--mono)}
.chat-progress{flex:0 0 auto;margin:0 max(24px,calc((100% - 920px)/2)) 10px;border:1px solid var(--accent-line);background:linear-gradient(90deg,var(--accent-dim),var(--bg-elevated));border-radius:9px;padding:11px 13px;display:flex;align-items:center;gap:14px}.chat-progress>div:first-child{display:grid;grid-template-columns:17px minmax(0,1fr);align-items:center;min-width:0}.chat-progress .pulse-dot{grid-row:1/3}.chat-progress strong{font-size:11px}.chat-progress small{margin-top:2px;color:var(--text-tertiary);font:8px var(--mono);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.chat-progress-actions{display:flex;gap:7px;margin-left:auto}.chat-progress .button{padding:7px 9px;font-size:10px}
.chat-composer{flex:0 0 auto;margin:0 max(24px,calc((100% - 920px)/2)) 20px;border:1px solid var(--border-strong);background:var(--bg-elevated);border-radius:11px;box-shadow:0 18px 42px rgba(0,0,0,.24);overflow:hidden}.chat-composer textarea{display:block;width:100%;min-height:56px;max-height:180px;resize:vertical;border:0;background:transparent;padding:14px 15px 8px;font-size:13px;line-height:1.5}.chat-composer textarea:focus{outline:0}.composer-actions{display:flex;align-items:center;gap:10px;padding:6px 8px 8px}.composer-actions>span{color:var(--text-tertiary);font:8px var(--mono)}.composer-actions>.button{margin-left:auto}.attach-button{width:31px;height:31px;border:1px solid var(--border);border-radius:7px;color:var(--text-secondary);display:grid;place-items:center;cursor:pointer}.attach-button:hover{border-color:var(--border-strong);color:var(--accent);background:var(--accent-dim)}.attach-button .icon{width:15px;height:15px}.attach-button input{display:none}
.selected-files{display:flex;flex-wrap:wrap;gap:5px;padding:8px 10px 0}.selected-files:empty{display:none}.selected-files>span{display:flex;align-items:center;gap:6px;max-width:260px;border:1px solid var(--border);border-radius:6px;background:var(--bg-surface);padding:5px 6px;color:var(--text-secondary)}.selected-files .icon{width:12px;height:12px;color:var(--accent)}.selected-files b{font-size:9px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.selected-files small{color:var(--text-tertiary);font:8px var(--mono);white-space:nowrap}.selected-files button{border:0;background:transparent;color:var(--text-tertiary);padding:2px;cursor:pointer}.selected-files button .icon{color:inherit;width:10px;height:10px}.chat-composer .form-error{margin:0;border-width:1px 0 0;border-radius:0}
.chat-empty{margin:auto;max-width:430px;padding:40px 24px;text-align:center}.chat-empty.compact{min-height:100%;display:flex;flex-direction:column;align-items:center;justify-content:center}.chat-empty-icon{width:36px;height:36px;color:var(--accent);margin:0 auto 17px}.chat-empty h2{margin:0;font-size:20px;font-weight:400;letter-spacing:-.02em}.chat-empty p{margin:9px 0 20px;color:var(--text-secondary);font-size:12px;line-height:1.6}.empty-action{text-align:center;margin-top:-24px}

@media(max-width:760px){
  .toolbar-right{margin-left:0;width:100%}
  .search-field,.search-field input{width:100%;min-width:0}
  .event-toggle{grid-template-columns:60px 54px minmax(0,1fr) auto!important}
  .event-toggle .event-category{display:none}
  .approval-rail>header,.approval-foot{display:block}.approval-count{display:inline-flex;margin:10px 0 0}.approval-context{align-items:flex-start}.approval-run{margin-left:0}.approval-actions{margin:12px 0 0}.approval-actions .button{flex:1}
  .hint{display:none}
  .content.chat-content{height:calc(100vh - 72px);padding:0}.chat-shell{grid-template-columns:1fr;grid-template-rows:auto minmax(0,1fr)}.session-rail{max-height:235px;border-right:0;border-bottom:1px solid var(--border-subtle)}.session-head{height:58px;padding:10px 14px}.session-head .eyebrow{display:none}.session-head h1{font-size:15px}.session-agent{padding:8px 12px 4px}.session-search{margin:4px 12px 7px}.session-list{display:flex;gap:5px;padding:2px 10px 10px;overflow:auto}.chat-session{min-width:180px;margin:0}.conversation-head{height:62px;padding:10px 14px}.conversation-meta span:not(.status){display:none}.message-scroll{padding:20px 13px}.message-body{max-width:88%}.chat-progress{margin:0 10px 8px}.chat-progress-actions a{display:none}.chat-composer{margin:0 10px 10px}.composer-actions>span{display:none}
}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
`;
