// GENERATED by packages/glove-image gallery-gen — do not edit by hand.
// Every image here was produced by glove-image in one scripted run; prompts,
// traces and costs are read verbatim from each asset's recorded Recipe.

export interface GalleryTraceEntry {
  enhancer: string;
  note?: string;
}

export interface GalleryShot {
  slug: string;
  file: string;
  width: number;
  height: number;
  title: string;
  set: string;
  intent: string;
  characters: string[];
  scene?: string;
  finalPrompt: string;
  trace: GalleryTraceEntry[];
  costUsd: number;
  kind: string;
  parent?: string;
  note?: string;
}

export interface GalleryCharacter {
  name: string;
  display_name: string;
  appearance: string;
  negative?: string;
  refCount: number;
}

export interface GalleryScene {
  name: string;
  label: string;
  setting: string;
}

export interface GalleryUsage {
  requests: number;
  tokens_in: number;
  tokens_out: number;
  cost_usd?: number;
}

export interface GalleryData {
  shots: GalleryShot[];
  characters: GalleryCharacter[];
  scenes: GalleryScene[];
  houseStyle: string;
  usage: { total: GalleryUsage; by_source: Record<string, GalleryUsage> };
}

export const gallery: GalleryData = {
  "shots": [
    {
      "slug": "packshot-kiondo",
      "file": "packshot-kiondo.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Product packshot on a clean white studio background: a handwoven Kenyan kiondo tote bag, natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and trim. Centred, no model, catalog lighting.\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters"
        },
        {
          "enhancer": "expand-scenes"
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0387264,
      "kind": "generated",
      "title": "Kiondo tote — packshot",
      "set": "inventory",
      "intent": "Product packshot: handwoven kiondo tote",
      "characters": [],
      "note": "Stands in for the photo a client would send. Pinned as the product's identity reference."
    },
    {
      "slug": "packshot-cuff",
      "file": "packshot-cuff.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Product packshot on a clean white studio background: a wide Maasai beaded cuff bracelet, dense rows of red, white, cobalt blue and green glass beads in a diamond pattern, brass edge trim. Centred, no model, catalog lighting.\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters"
        },
        {
          "enhancer": "expand-scenes"
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0387483,
      "kind": "generated",
      "title": "Beaded cuff — packshot",
      "set": "inventory",
      "intent": "Product packshot: Maasai beaded cuff",
      "characters": [],
      "note": "Second inventory item, same treatment."
    },
    {
      "slug": "consistency-kilimani-rooftop",
      "file": "consistency-kilimani-rooftop.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391692,
      "kind": "generated",
      "title": "Kilimani rooftop",
      "set": "consistency",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "kilimani-rooftop"
    },
    {
      "slug": "consistency-karura-forest",
      "file": "consistency-karura-forest.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a red-earth path in Karura Forest, Nairobi, tall indigenous trees, dappled green light through the canopy, soft mist in the deep background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"karura-forest\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0778505,
      "kind": "generated",
      "title": "Karura Forest",
      "set": "consistency",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "karura-forest"
    },
    {
      "slug": "consistency-maasai-market",
      "file": "consistency-maasai-market.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: the Maasai Market in Nairobi, rows of stalls hung with beadwork and bright printed cloth, midday sun with strong colour, busy but softly blurred behind the subject\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"maasai-market\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0392186,
      "kind": "generated",
      "title": "Maasai Market",
      "set": "consistency",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "maasai-market"
    },
    {
      "slug": "consistency-nairobi-street",
      "file": "consistency-nairobi-street.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Nairobi CBD side street in the late afternoon, low colonial-era shopfronts, a matatu passing in soft motion blur, long warm shadows across the pavement\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"nairobi-street\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391464,
      "kind": "generated",
      "title": "CBD side street",
      "set": "consistency",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "nairobi-street"
    },
    {
      "slug": "consistency-nairobi-national-park",
      "file": "consistency-nairobi-national-park.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: the open golden grassland of Nairobi National Park at early morning, flat-topped acacia trees, the city skyline faint on the far horizon, cool clear light\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"nairobi-national-park\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391633,
      "kind": "generated",
      "title": "Nairobi National Park",
      "set": "consistency",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "nairobi-national-park"
    },
    {
      "slug": "matrix-kilimani-rooftop",
      "file": "matrix-kilimani-rooftop.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara resting one hand on a railing, the beaded cuff clearly visible on her wrist, three-quarter view\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nBeaded Cuff: a wide Maasai beaded cuff bracelet worn on the wrist, dense rows of red, white, cobalt blue and green glass beads in a diamond pattern with brass edge trim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.039167,
      "kind": "generated",
      "title": "Beaded cuff · Kilimani rooftop",
      "set": "matrix",
      "intent": "Amara resting one hand on a railing, the beaded cuff clearly visible on her wrist",
      "characters": [
        "amara",
        "beaded-cuff"
      ],
      "scene": "kilimani-rooftop"
    },
    {
      "slug": "matrix-karura-forest",
      "file": "matrix-karura-forest.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara resting one hand on a railing, the beaded cuff clearly visible on her wrist, three-quarter view\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nBeaded Cuff: a wide Maasai beaded cuff bracelet worn on the wrist, dense rows of red, white, cobalt blue and green glass beads in a diamond pattern with brass edge trim\n\nSetting: a red-earth path in Karura Forest, Nairobi, tall indigenous trees, dappled green light through the canopy, soft mist in the deep background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"karura-forest\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391458,
      "kind": "generated",
      "title": "Beaded cuff · Karura Forest",
      "set": "matrix",
      "intent": "Amara resting one hand on a railing, the beaded cuff clearly visible on her wrist",
      "characters": [
        "amara",
        "beaded-cuff"
      ],
      "scene": "karura-forest"
    },
    {
      "slug": "matrix-maasai-market",
      "file": "matrix-maasai-market.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara resting one hand on a railing, the beaded cuff clearly visible on her wrist, three-quarter view\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nBeaded Cuff: a wide Maasai beaded cuff bracelet worn on the wrist, dense rows of red, white, cobalt blue and green glass beads in a diamond pattern with brass edge trim\n\nSetting: the Maasai Market in Nairobi, rows of stalls hung with beadwork and bright printed cloth, midday sun with strong colour, busy but softly blurred behind the subject\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"maasai-market\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391464,
      "kind": "generated",
      "title": "Beaded cuff · Maasai Market",
      "set": "matrix",
      "intent": "Amara resting one hand on a railing, the beaded cuff clearly visible on her wrist",
      "characters": [
        "amara",
        "beaded-cuff"
      ],
      "scene": "maasai-market"
    },
    {
      "slug": "multi-kilimani-rooftop",
      "file": "multi-kilimani-rooftop.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara standing, kiondo tote over one shoulder and the beaded cuff on the opposite wrist, full length\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\nBeaded Cuff: a wide Maasai beaded cuff bracelet worn on the wrist, dense rows of red, white, cobalt blue and green glass beads in a diamond pattern with brass edge trim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 3 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0389313,
      "kind": "generated",
      "title": "Full look · Kilimani rooftop",
      "set": "multi",
      "intent": "Amara standing, kiondo tote over one shoulder and the beaded cuff on the opposite wrist",
      "characters": [
        "amara",
        "kiondo-tote",
        "beaded-cuff"
      ],
      "scene": "kilimani-rooftop"
    },
    {
      "slug": "multi-karura-forest",
      "file": "multi-karura-forest.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara standing, kiondo tote over one shoulder and the beaded cuff on the opposite wrist, full length\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\nBeaded Cuff: a wide Maasai beaded cuff bracelet worn on the wrist, dense rows of red, white, cobalt blue and green glass beads in a diamond pattern with brass edge trim\n\nSetting: a red-earth path in Karura Forest, Nairobi, tall indigenous trees, dappled green light through the canopy, soft mist in the deep background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 3 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"karura-forest\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0389901,
      "kind": "generated",
      "title": "Full look · Karura Forest",
      "set": "multi",
      "intent": "Amara standing, kiondo tote over one shoulder and the beaded cuff on the opposite wrist",
      "characters": [
        "amara",
        "kiondo-tote",
        "beaded-cuff"
      ],
      "scene": "karura-forest"
    },
    {
      "slug": "tweak-at-dusk",
      "file": "tweak-at-dusk.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera. at dusk, city lights just coming on\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391494,
      "kind": "generated",
      "title": "at dusk",
      "set": "regenerate",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera. at dusk, city lights just coming on",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "kilimani-rooftop",
      "parent": "consistency-kilimani-rooftop",
      "note": "One call. The recipe — characters, scene, style, params — is replayed from the asset."
    },
    {
      "slug": "tweak-in-soft-rain",
      "file": "tweak-in-soft-rain.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera. in soft rain, wet terrace reflecting the light\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat, blurry product, distorted hands, text overlay, watermark",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "negative-defaults"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391497,
      "kind": "generated",
      "title": "in soft rain",
      "set": "regenerate",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera. in soft rain, wet terrace reflecting the light",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "kilimani-rooftop",
      "parent": "consistency-kilimani-rooftop",
      "note": "One call. The recipe — characters, scene, style, params — is replayed from the asset."
    },
    {
      "slug": "edit-indigo",
      "file": "edit-indigo.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Change only the linen jumpsuit to a deep indigo blue. Keep the model, the bag, the pose and the background identical.",
      "trace": [],
      "costUsd": 0.0391411,
      "kind": "edited",
      "title": "Colourway swap",
      "set": "edit",
      "intent": "Change only the jumpsuit to deep indigo",
      "characters": [],
      "parent": "consistency-kilimani-rooftop",
      "note": "Edit records its parent, so the lineage of any frame is recoverable."
    },
    {
      "slug": "style-editorial",
      "file": "style-editorial.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail\n\nAvoid: no sunglasses, no hat",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391684,
      "kind": "generated",
      "title": "Editorial catalog",
      "set": "style",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "kilimani-rooftop",
      "note": "styleDirective(\"editorial fashion catalog photography, natural daylight, sha…\")"
    },
    {
      "slug": "style-film",
      "file": "style-film.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: shot on grainy 35mm film, muted kodak portra palette, soft halation, slight vignette\n\nAvoid: no sunglasses, no hat",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391437,
      "kind": "generated",
      "title": "Grainy 35mm film",
      "set": "style",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "kilimani-rooftop",
      "note": "styleDirective(\"shot on grainy 35mm film, muted kodak portra palette, soft h…\")"
    },
    {
      "slug": "style-studio",
      "file": "style-studio.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: high-key studio lighting on seamless backdrop, crisp shadowless product lighting, minimal and clean\n\nAvoid: no sunglasses, no hat",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391425,
      "kind": "generated",
      "title": "High-key studio",
      "set": "style",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "kilimani-rooftop",
      "note": "styleDirective(\"high-key studio lighting on seamless backdrop, crisp shadowl…\")"
    },
    {
      "slug": "style-gouache",
      "file": "style-gouache.webp",
      "width": 768,
      "height": 768,
      "finalPrompt": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera\n\nCharacters (keep these descriptions exact):\nAmara: a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals\nKiondo Tote: a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim\n\nSetting: a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background\n\nStyle: hand-painted gouache illustration, muted palette, visible brush texture, soft rim light\n\nAvoid: no sunglasses, no hat",
      "trace": [
        {
          "enhancer": "expand-characters",
          "note": "Expanded 2 character(s)."
        },
        {
          "enhancer": "expand-scenes",
          "note": "Expanded scene \"kilimani-rooftop\"."
        },
        {
          "enhancer": "style-directive"
        },
        {
          "enhancer": "fit-to-model",
          "note": "No negative-prompt slot — folded into the prompt as an Avoid clause."
        }
      ],
      "costUsd": 0.0391422,
      "kind": "generated",
      "title": "Hand-painted gouache",
      "set": "style",
      "intent": "Amara walking, carrying the kiondo tote on her shoulder, looking off camera",
      "characters": [
        "amara",
        "kiondo-tote"
      ],
      "scene": "kilimani-rooftop",
      "note": "styleDirective(\"hand-painted gouache illustration, muted palette, visible br…\")"
    }
  ],
  "characters": [
    {
      "name": "amara",
      "display_name": "Amara",
      "appearance": "a Kenyan woman in her late 20s, warm dark brown skin, short natural afro, delicate gold hoop earrings, wearing a fitted cream linen jumpsuit and tan leather sandals",
      "negative": "no sunglasses, no hat",
      "refCount": 0
    },
    {
      "name": "kiondo-tote",
      "display_name": "Kiondo Tote",
      "appearance": "a handwoven Kenyan kiondo tote bag in natural cream sisal with a band of burnt-orange and black geometric pattern, tan leather handles and tan leather trim at the rim",
      "refCount": 1
    },
    {
      "name": "beaded-cuff",
      "display_name": "Beaded Cuff",
      "appearance": "a wide Maasai beaded cuff bracelet worn on the wrist, dense rows of red, white, cobalt blue and green glass beads in a diamond pattern with brass edge trim",
      "refCount": 1
    }
  ],
  "scenes": [
    {
      "name": "kilimani-rooftop",
      "label": "Kilimani rooftop",
      "setting": "a Kilimani rooftop terrace in Nairobi at golden hour, low warm sun, potted palms and bougainvillea, the city skyline and jacaranda canopy soft in the background"
    },
    {
      "name": "karura-forest",
      "label": "Karura Forest",
      "setting": "a red-earth path in Karura Forest, Nairobi, tall indigenous trees, dappled green light through the canopy, soft mist in the deep background"
    },
    {
      "name": "maasai-market",
      "label": "Maasai Market",
      "setting": "the Maasai Market in Nairobi, rows of stalls hung with beadwork and bright printed cloth, midday sun with strong colour, busy but softly blurred behind the subject"
    },
    {
      "name": "nairobi-street",
      "label": "CBD side street",
      "setting": "a Nairobi CBD side street in the late afternoon, low colonial-era shopfronts, a matatu passing in soft motion blur, long warm shadows across the pavement"
    },
    {
      "name": "nairobi-national-park",
      "label": "Nairobi National Park",
      "setting": "the open golden grassland of Nairobi National Park at early morning, flat-topped acacia trees, the city skyline faint on the far horizon, cool clear light"
    }
  ],
  "houseStyle": "editorial fashion catalog photography, natural daylight, shallow depth of field, full-body framing, sharp product detail",
  "usage": {
    "total": {
      "requests": 19,
      "tokens_in": 23851,
      "tokens_out": 25914,
      "cost_usd": 0.7814403
    },
    "by_source": {
      "generate": {
        "requests": 18,
        "tokens_in": 22514,
        "tokens_out": 24608,
        "cost_usd": 0.7422991999999999
      },
      "edit": {
        "requests": 1,
        "tokens_in": 1337,
        "tokens_out": 1306,
        "cost_usd": 0.0391411
      }
    }
  }
};
